language: r
cache: packages
latex: false

jobs:
  include:
  - r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("pammtools", dependencies = TRUE)'
    - Rscript -e 'remotes::install_cran("TBFmultinomial", dependencies = TRUE)'
    - Rscript -e 'remotes::install_github("jimhester/covr")'
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_cran("scam")'
    - Rscript -e 'remotes::install_cran("RColorBrewer")'
    - Rscript -e 'remotes::install_cran("timereg")'
    - Rscript -e 'remotes::install_cran("grid")'
    - Rscript -e 'remotes::install_cran("gridExtra")'
    - Rscript -e 'remotes::install_cran("coxme")'
    - Rscript -e 'remotes::install_cran("knitr")'
    - Rscript -e 'remotes::install_cran("rmarkdown")'
    - Rscript -e 'remotes::install_cran("pec")'
    - Rscript -e 'remotes::install_cran("devtools")'
    - Rscript -e 'remotes::install_cran("etm")'
# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov(type="all", line_exclusions="R/zzz.R")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: false
  local_dir: docs
  on:
    all_branches: true
