language: r
sudo: false
cache: packages

r:
  - devel
  - release

r_github_packages:
  - jimhester/covr
  - tidyverse/dplyr
  - tidyverse/purrr

after_success:
  - Rscript -e 'covr::codecov(type="all", line_exclusions="R/zzz.R")'