language: r
sudo: false
cache: packages

r:
  - devel
  - release

r_packages:
  - pammtools # for building pkgdown vignettes via travis
  - TBFmultinomial

r_github_packages:
  - jimhester/covr
  - thomasp85/patchwork

# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov(type="all", line_exclusions="R/zzz.R")'
  - Rscript -e 'pkgdown::build_site()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  github-token: $GITHUB_PAT
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
