language: R
sudo: false
cache: packages
fortran: false
latex: false

jobs:
  include:
  - r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("pammtools", dependencies = TRUE)'
    - Rscript -e 'remotes::install_cran("TBFmultinomial", dependencies = TRUE)'
    - Rscript -e 'remotes::install_github("jimhester/covr")'
    - Rscript -e 'remotes::install_github("jimhester/covr", dependencies = TRUE)'

# whitelist
branches:
  only:
    - master

after_success:
  - Rscript -e 'covr::codecov(type="all", line_exclusions="R/zzz.R")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: false
  local-dir: docs
  on:
    branch: master
